version: '2'
services:
  first_service:
    image: alpine
    command: sh -c "sleep 5; nc -lk -p 11111 0.0.0.0"

  second_service:
    image: alpine
    command: sh -c "sleep 8; nc -lk -p 22222 0.0.0.0"

  app:
    build: .
    environment:
      - WAIT_SERVICES=first_service:11111,second_service:22222
      - WAIT_ATTEMPTS=10
    depends_on:
      - first_service
      - second_service
    command: sh -c "wait-services && nc -z first_service 11111 && echo Connected"
